### PR TITLE
57 customer app header

### PR DESCRIPTION
**Pull request by FengyanTina**

### CODE REVIEW

**Comment by FengyanTina** [comment]
1. Custom header for stack screen and Tab screens
2. pass in the house name as params in custom header
3. Fix the rerender bug in custom header title
4. add a function in profilescreen to pass in the 
 const [headerTitle, setHeaderTitle] = useState<string>("TinaHome");
  useEffect(() => {
    if (profile) {
      const household = households.find((h) => h.id === profile.householdId);
      if (household) {
        setHeaderTitle(household.name);
      }
    }
  }, [profile]);
5. made styles for the header 
6. Arrows to go back and go forward
7. BeeHome icon to go to household list

**Review by Ellik90 — COMMENTED** [review]
i approve and merge =)

**Review by Ellik90 — APPROVED** [review]

**Comment by FengyanTina** [comment]
pull from main again and reolved conflicts

**Review by Ellik90 — COMMENTED** [review]
grejt

**Review by Ellik90 — COMMENTED** [review]
very good

**Review by Ellik90 — DISMISSED** [review]

**Review by Ellik90 — COMMENTED** [review]
wohooo

**Review by Ellik90 — APPROVED** [review]

**Pull request merged**
