### PR TITLE
255 moving edit function to household screen and avatar only shows when is owner

### PR DESCRIPTION
**Pull request by FengyanTina**
1. moved edit house name function to householdAccount from ProfileScreen
2. change the avatars so that in frond of each house,  it is renders the avatar of the activeUser in that house
3. styles the screen and edited(only the one that is clicked is going to change to edit form the rest remain the same)
4. rerender the household list after editing the name, so the list is refreshed

### CODE REVIEW

**Comment by Fiffigelin** [comment]
image

Avatar shows correctly but not the edit-pen

**Comment by FengyanTina** [comment]
yes, i was going to change that as well, so only show edit when is owner, but i think there might be a bug in that activeprofile, as in householdTask screen, when checking if activeprofile isOwner does not do its job, in other work, it shows the bee avatar in profile screen which means the person should be owner, but when come to task screen, checking if it is owner failed.

**Comment by FengyanTina** [comment]
i need to investigate more before i can conclude anything, i am not very sure about where is the problem yet

**Comment by FengyanTina** [comment]
redo this issue again

**Comment by Fiffigelin** [comment]
Closing this pr - to far from main

**Pull request closed without merging**
